name: Build Debug APK

on:
  workflow_dispatch:   # ручной запуск (кнопка)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myvpn-debug-apk
          path: app/build/outputs/apk/debug/*.apk
