[versions]
androidGradlePlugin = "8.5.0"
kotlin = "1.9.22"
androidxCore = "1.12.0"
androidxAppcompat = "1.6.1"
androidxActivity = "1.8.0"
constraintlayout = "2.1.4"
preferenceKtx = "1.2.1"
recyclerview = "1.3.2"
swiperefreshlayout = "1.1.0"
viewpager2 = "1.0.0"
fragment = "1.6.2"
material = "1.11.0"
toasty = "1.5.2"
editorkit = "1.1.0"
flexbox = "3.0.0"
mmkvStatic = "1.3.4"
gson = "2.10.1"
okhttp = "4.12.0"
coroutines = "1.7.3"
languageBase = "1.2.0"
languageJson = "1.2.0"
quickieFoss = "1.4.0"
core = "1.12.0"
lifecycle = "2.7.0"
work = "2.9.0"
multidex = "2.0.1"
desugar = "2.0.4"
junit = "4.13.2"
androidxJunit = "1.1.5"
espresso = "3.5.1"
mockitoInline = "5.2.0"
mockitoKotlin = "4.1.0"
licensePlugin = "0.11.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidxActivity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
toasty = { group = "com.github.GrenderG", name = "Toasty", version.ref = "toasty" }
editorkit = { group = "io.github.rosemoe.sora-editor", name = "editor", version.ref = "editorkit" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
mmkv-static = { group = "com.tencent", name = "mmkv-static", version.ref = "mmkvStatic" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
language-base = { group = "com.github.2dust", name = "language-base", version.ref = "languageBase" }
language-json = { group = "com.github.2dust", name = "language-json", version.ref = "languageJson" }
quickie-foss = { group = "com.github.2dust", name = "quickie-foss", version.ref = "quickieFoss" }
core = { group = "com.github.2dust", name = "core", version.ref = "core" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
work-multiprocess = { group = "androidx.work", name = "work-multiprocess", version.ref = "work" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
org-mockito-mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gradle-license-plugin = { id = "com.jaredsburrows.license", version.ref = "licensePlugin" }
